name: "AWS S3 Sync with CloudFront Cache invalidation & wait for deployment"
description: "Sync a directory to an AWS S3 bucket and invalidate the CloudFront cache & wait for deployment"
author: kersvers
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
